/**
 * Component Forge v1.0 — EN/FR
 */
(function() {
'use strict';
var TX = {
  en: {
    tab: 'Forge', title: '🧩 Component Forge', sub: 'Web Components Builder',
    cat: 'Category', variant: 'Variant', color: 'Color Scheme', inject: '⚡ Inject Component',
    save: '💾 Save to Library', saved: 'My Library', empty: 'Library is empty.',
    injected: '✅ Component injected!'
  },
  fr: {
    tab: 'Forge', title: '🧩 Forjă de Componente', sub: 'Constructeur Web Components',
    cat: 'Catégorie', variant: 'Variante', color: 'Thème', inject: '⚡ Injecter Composant',
    save: '💾 Sauvegarder', saved: 'Ma Bibliothèque', empty: 'Bibliothèque vide.',
    injected: '✅ Composant injecté !'
  }
};

function gl() { return window.lang || 'en'; }
function t(k) { return (TX[gl()] || TX.en)[k] || k; }

var state = { cat: 'Card', variant: 'glass', color: '#3b82f6', lib: JSON.parse(localStorage.getItem('ia_forge_lib')||'[]') };

var COMPS = {
  Card: {
    glass: '<div class="forge-card" style="background:rgba(255,255,255,0.05);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,0.1);border-radius:16px;padding:24px;color:#fff;">\n  <h3 style="margin:0 0 10px;color:COLOR;">Card Title</h3>\n  <p style="margin:0;opacity:0.8;font-size:14px;">Glassmorphism component generated by Forge.</p>\n</div>',
    solid: '<div class="forge-card" style="background:COLOR;border-radius:12px;padding:24px;color:#fff;box-shadow:0 10px 30px rgba(0,0,0,0.2);">\n  <h3 style="margin:0 0 10px;">Solid Card</h3>\n  <p style="margin:0;opacity:0.9;font-size:14px;">Solid color component.</p>\n</div>'
  },
  Button: {
    glass: '<button class="forge-btn" style="background:rgba(255,255,255,0.1);backdrop-filter:blur(5px);border:1px solid rgba(255,255,255,0.2);border-radius:8px;padding:12px 24px;color:COLOR;font-weight:700;cursor:pointer;transition:0.3s;">Glass Button</button>',
    solid: '<button class="forge-btn" style="background:COLOR;border:none;border-radius:8px;padding:12px 24px;color:#fff;font-weight:900;cursor:pointer;box-shadow:0 5px 15px rgba(0,0,0,0.3);transition:0.3s;">Solid Button</button>'
  },
  Badge: {
    glass: '<span class="forge-badge" style="background:rgba(255,255,255,0.1);border:1px solid COLOR;border-radius:20px;padding:4px 12px;color:COLOR;font-size:12px;font-weight:800;">Badge</span>',
    solid: '<span class="forge-badge" style="background:COLOR;border-radius:20px;padding:4px 12px;color:#fff;font-size:12px;font-weight:800;">Badge</span>'
  }
};

function getCode() {
  var c = COMPS[state.cat][state.variant].replace(/COLOR/g, state.color);
  return '<!-- 🧩 Forge: ' + state.cat + ' (' + state.variant + ') -->\n' + c;
}

function injectCode(codeStr) {
  if(!window.editor) return;
  var code = window.editor.getValue();
  code = code.includes('</body>') ? code.replace('</body>', codeStr + '\n</body>') : code + '\n' + codeStr;
  window.editor.setValue(code);
  if(window.runPreview) window.runPreview();
  if(window.showToast) window.showToast(t('injected'));
}

function saveToLib() {
  state.lib.push({ cat: state.cat, v: state.variant, c: state.color, code: getCode() });
  localStorage.setItem('ia_forge_lib', JSON.stringify(state.lib));
  renderForgeTab();
}

function renderForgeTab() {
  var parent = document.getElementById('left-body');
  if(!parent) return;
  parent.innerHTML = '';
  var wrap = document.createElement('div');
  wrap.style = 'display:flex;flex-direction:column;height:100%;overflow:hidden;';

  var hdr = document.createElement('div');
  hdr.style = 'padding:12px 14px 8px;border-bottom:1px solid rgba(234,179,8,0.25);flex-shrink:0;';
  hdr.innerHTML = '<div style="font-size:13px;font-weight:900;color:#eab308;">' + t('title') + '</div><div style="font-size:10px;color:#64748b;margin-top:2px;">' + t('sub') + '</div>';
  wrap.appendChild(hdr);

  var body = document.createElement('div');
  body.style = 'flex:1;overflow-y:auto;padding:12px;display:flex;flex-direction:column;gap:12px;';

  // Builder
  var build = document.createElement('div');
  build.style = 'background:rgba(234,179,8,0.05);border:1px solid rgba(234,179,8,0.15);border-radius:8px;padding:10px;';
  
  function makeSel(label, id, opts) {
    var d = document.createElement('div'); d.style='margin-bottom:8px;';
    d.innerHTML = '<div style="font-size:9px;color:#94a3b8;margin-bottom:4px;">'+label+'</div>';
    var sel = document.createElement('select');
    sel.style = 'width:100%;background:rgba(0,0,0,0.3);border:1px solid rgba(255,255,255,0.1);border-radius:6px;padding:6px;color:#fff;font-size:11px;outline:none;';
    opts.forEach(function(o) {
      var opt = document.createElement('option'); opt.value = o; opt.textContent = o;
      if(state[id]===o) opt.selected=true; sel.appendChild(opt);
    });
    sel.onchange = function(){ state[id] = sel.value; renderForgeTab(); };
    d.appendChild(sel); return d;
  }

  build.appendChild(makeSel(t('cat'), 'cat', Object.keys(COMPS)));
  build.appendChild(makeSel(t('variant'), 'variant', ['glass', 'solid']));

  var cRow = document.createElement('div'); cRow.style='display:flex;align-items:center;gap:8px;margin-bottom:10px;';
  cRow.innerHTML = '<div style="font-size:9px;color:#94a3b8;flex:1;">'+t('color')+'</div>';
  var cInp = document.createElement('input'); cInp.type='color'; cInp.value=state.color;
  cInp.style='width:30px;height:26px;border:none;border-radius:4px;cursor:pointer;padding:0;background:none;';
  cInp.oninput = function() { state.color=cInp.value; };
  cRow.appendChild(cInp); build.appendChild(cRow);

  var pLbl = document.createElement('div'); pLbl.style='font-size:9px;color:#94a3b8;margin-bottom:6px;'; pLbl.textContent = 'Preview';
  build.appendChild(pLbl);
  var prev = document.createElement('div');
  prev.style = 'background:#0f172a;border-radius:6px;padding:15px;display:flex;align-items:center;justify-content:center;border:1px solid rgba(255,255,255,0.05);margin-bottom:12px;';
  prev.innerHTML = getCode();
  build.appendChild(prev);

  var bInj = document.createElement('button'); bInj.textContent = t('inject');
  bInj.style='width:100%;background:linear-gradient(135deg,#eab308,#ca8a04);border:none;border-radius:6px;padding:8px;color:#fff;font-weight:900;font-size:11px;cursor:pointer;margin-bottom:6px;';
  bInj.onclick=function(){ injectCode(getCode()); };
  build.appendChild(bInj);

  var bSav = document.createElement('button'); bSav.textContent = t('save');
  bSav.style='width:100%;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:6px;padding:8px;color:#cbd5e1;font-weight:700;font-size:10px;cursor:pointer;';
  bSav.onclick=saveToLib;
  build.appendChild(bSav);

  body.appendChild(build);

  // Library
  var libSec = document.createElement('div');
  libSec.innerHTML = '<div style="font-size:9px;font-weight:900;color:#94a3b8;text-transform:uppercase;margin-bottom:8px;">'+t('saved')+'</div>';
  var list = document.createElement('div');
  list.style = 'display:flex;flex-direction:column;gap:6px;';
  if(state.lib.length===0) list.innerHTML='<div style="font-size:10px;color:#64748b;font-style:italic;">'+t('empty')+'</div>';
  else {
    state.lib.forEach(function(item, idx) {
      var d = document.createElement('div');
      d.style='background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.05);border-radius:6px;padding:8px;display:flex;justify-content:space-between;align-items:center;cursor:pointer;';
      d.innerHTML = '<div style="font-size:10px;color:#fff;font-weight:700;"><span style="color:'+item.c+';margin-right:4px;">●</span>'+item.cat+' ('+item.v+')</div>';
      var inj = document.createElement('button'); inj.textContent='+';
      inj.style='background:#eab308;color:#000;border:none;border-radius:4px;width:20px;height:20px;font-weight:900;cursor:pointer;';
      inj.onclick = function(e){ e.stopPropagation(); injectCode(item.code); };
      d.appendChild(inj);
      list.appendChild(d);
    });
  }
  libSec.appendChild(list);
  body.appendChild(libSec);

  wrap.appendChild(body);
  parent.appendChild(wrap);
}

document.addEventListener('DOMContentLoaded', function() {
  var oAL = window.applyLang;
  window.applyLang = function() {
    if(typeof oAL==='function') oAL();
    var el = document.getElementById('lbl-tab-forge');
    if(el) el.textContent = t('tab');
    if(window.activeTab==='forge') renderForgeTab();
  };

  var oRT = window.renderTab;
  window.renderTab = function(tab) {
    if(tab==='forge') {
      window.activeTab = 'forge';
      document.querySelectorAll('.ltab').forEach(function(b){b.classList.remove('active');});
      var btn = document.getElementById('tab-forge');
      if(btn) btn.classList.add('active');
      renderForgeTab();
      return;
    }
    if(typeof oRT==='function') oRT(tab);
  };
});
})();
