(function(){
'use strict';
var T={
  en:{tab:'Data Forge',title:'📦 Data Forge',sub:'JSON to TS/Zod Converter',btnRun:'⚙️ Convert JSON',lbl1:'Paste JSON payload:',msg:'Generated in editor.'},
  fr:{tab:'Forge de Données',title:'📦 Forge de Données',sub:'Convertisseur JSON vers TS/Zod',btnRun:'⚙️ Convertir JSON',lbl1:'Collez le payload JSON:',msg:'Généré dans l\'éditeur.'}
};
function tl(k){return (T[window.lang||'en']||T.en)[k]||k;}

function renderTab(){
  var p=document.getElementById('left-body');if(!p)return;
  p.innerHTML='';
  var w=document.createElement('div');w.style='display:flex;flex-direction:column;height:100%;background:#0c0f1a;';
  var h=document.createElement('div');h.style='padding:12px 14px;border-bottom:1px solid rgba(129,140,248,0.3);background:linear-gradient(135deg,rgba(55,48,163,0.3),rgba(129,140,248,0.06));';
  h.innerHTML='<div style="font-size:13px;font-weight:900;color:#818cf8;">'+tl('title')+'</div><div style="font-size:10px;color:#64748b;margin-top:2px;">'+tl('sub')+'</div>';
  w.appendChild(h);
  var b=document.createElement('div');b.style='flex:1;overflow-y:auto;padding:12px;display:flex;flex-direction:column;gap:10px;';
  
  var lbl1=document.createElement('div');lbl1.style='font-size:11px;color:#94a3b8;';lbl1.innerText=tl('lbl1');
  b.appendChild(lbl1);
  
  var inp=document.createElement('textarea');
  inp.placeholder='{\n  "id": 1,\n  "name": "Alex",\n  "active": true\n}';
  inp.style='width:100%;height:150px;background:#0f172a;border:1px solid #334155;color:#e2e8f0;padding:8px;border-radius:6px;font-size:11px;font-family:monospace;outline:none;resize:none;';
  b.appendChild(inp);

  var btn=document.createElement('button');btn.innerHTML=tl('btnRun');
  btn.style='width:100%;background:linear-gradient(135deg,#3730a3,#6366f1);color:#fff;border:none;padding:10px;border-radius:8px;font-size:11px;font-weight:900;cursor:pointer;box-shadow:0 4px 15px rgba(99,102,241,0.3);margin-top:5px;';
  b.appendChild(btn);

  btn.onclick=function(){
    var val = inp.value.trim();
    if(!val) return;
    try {
      var obj = JSON.parse(val);
      var ts = 'interface AutoGenerated {\n';
      var zod = 'const Schema = z.object({\n';
      for(var k in obj){
        var t = typeof obj[k];
        if(Array.isArray(obj[k])) t = 'any[]';
        ts += '  ' + k + ': ' + t + ';\n';
        var zt = t==='number'?'z.number()':t==='boolean'?'z.boolean()':t==='any[]'?'z.array(z.any())':'z.string()';
        zod += '  ' + k + ': ' + zt + ',\n';
      }
      ts += '}\n';
      zod += '});\n';
      
      if(window.editor) {
        var current = window.editor.getValue();
        window.editor.setValue(current + '\n\n// --- Data Forge Generated ---\n\n' + ts + '\n' + zod);
      }
      btn.innerText = tl('msg');
      setTimeout(function(){btn.innerHTML=tl('btnRun');}, 2000);
    } catch(e) {
      alert("Invalid JSON");
    }
  };
  w.appendChild(b);p.appendChild(w);
}
document.addEventListener('DOMContentLoaded',function(){
  var oAL=window.applyLang;window.applyLang=function(){if(typeof oAL==='function')oAL();var el=document.getElementById('lbl-tab-dataforge');if(el)el.textContent=tl('tab');if(window.activeTab==='dataforge')renderTab();};
  var oRT=window.renderTab;window.renderTab=function(t){if(t==='dataforge'){window.activeTab='dataforge';document.querySelectorAll('.ltab').forEach(function(b){b.classList.remove('active');});var btn=document.getElementById('tab-dataforge');if(btn)btn.classList.add('active');renderTab();return;}if(typeof oRT==='function')oRT(t);};
});
})();
