import JSZip from 'jszip';
import { saveAs } from 'file-saver';

/**
 * Generates a standard PWA manifest file.
 */
export const generatePwaManifest = (appName = 'AuraGen App') => {
    const manifest = {
        name: appName,
        short_name: 'AuraGen',
        description: 'Professional app generated by AuraGen AI',
        start_url: '.',
        display: 'standalone',
        background_color: '#ffffff',
        theme_color: '#6366f1',
        icons: [
            {
                src: 'https://cdn-icons-png.flaticon.com/512/2583/2583091.png',
                sizes: '512x512',
                type: 'image/png',
                purpose: 'any maskable'
            }
        ]
    };
    return JSON.stringify(manifest, null, 2);
};

/**
 * Generates a simple Service Worker for basic PWA support.
 */
export const generateServiceWorker = () => {
    return `
const CACHE_NAME = 'auragen-v1';
const ASSETS = [
  '/',
  '/index.html',
  '/manifest.json'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS);
    })
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
    `.trim();
};

/**
 * Creates a professional ZIP bundle with separate HTML, CSS, and JS.
 */
export const downloadProjectZip = async (code, files = [], options = {}) => {
    const zip = new JSZip();
    
    // Extract CSS content
    const cssContent = files.filter(f => f.name.endsWith('.css')).map(f => f.content).join('\n');
    
    // Extract JS files (excluding main App.jsx if we bundle it in index.html)
    const extraJsContent = files
        .filter(f => f.name !== 'App.jsx' && (f.name.endsWith('.jsx') || f.name.endsWith('.js')))
        .map(f => `/* File: ${f.name} */\n${f.content.replace(/export default\s+/g, 'const ' + f.name.replace(/\.[^/.]+$/, "") + ' = ').replace(/export\s+/g, '')}`)
        .join('\n\n');

    // Create index.html
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${options.title || 'AuraGen Export'}</title>
  
  <!-- PWA Support -->
  <link rel="manifest" href="manifest.json">
  <meta name="theme-color" content="#6366f1">
  <link rel="apple-touch-icon" href="https://cdn-icons-png.flaticon.com/512/2583/2583091.png">

  <!-- Style -->
  <link rel="stylesheet" href="style.css">
  
  <!-- CDNs for React and Babel -->
  <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
</head>
<body>
  <div id="root"></div>
  
  <!-- Main Script -->
  <script type="text/babel">
    /* Global Extras */
    ${extraJsContent}

    /* App Core */
    ${code}
    
    const root = ReactDOM.createRoot(document.getElementById('root'));
    root.render(<App />);

    /* Service Worker Registration */
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', () => {
        navigator.serviceWorker.register('sw.js');
      });
    }
  </script>
</body>
</html>`;

    // Add files to ZIP
    zip.file('index.html', html);
    zip.file('style.css', cssContent || '/* Add your styles here */');
    zip.file('manifest.json', generatePwaManifest(options.title));
    zip.file('sw.js', generateServiceWorker());
    
    // Add GitHub/Netlify specific metadata if requested
    if (options.netlify) {
        zip.file('netlify.toml', '[[redirects]]\n  from = "/*"\n  to = "/index.html"\n  status = 200');
    }

    const content = await zip.generateAsync({ type: 'blob' });
    saveAs(content, options.filename || 'auragen-app.zip');
};
