import ALL_VAULT_ITEMS from '../components/CodeVault';

// Simulating a unified indexer
const buildIndex = () => {
    const index = [];
    
    // Add Vault Items
    if (ALL_VAULT_ITEMS) {
        ALL_VAULT_ITEMS.forEach(item => {
            index.push({
                source: 'Vault',
                id: item.id,
                name: item.name,
                nameFr: item.nameFr,
                tags: item.tags || [],
                code: item.code
            });
        });
    }

    return index;
};

const omniIndex = buildIndex();

export const searchOmniIndex = (keywords) => {
    const lowerKeywords = keywords.toLowerCase().split(' ');
    
    return omniIndex.filter(item => {
        const searchableText = `${item.name} ${item.nameFr} ${item.tags.join(' ')}`.toLowerCase();
        return lowerKeywords.some(kw => searchableText.includes(kw));
    });
};

export const synthesizeApp = async (prompt, onProgress, isFr = false) => {
    const p = prompt.toLowerCase();
    
    onProgress(isFr ? 'Analyse de la base de données Vault et de l\'intention...' : 'Analyzing Vault database and user intent...', 'search');
    await new Promise(r => setTimeout(r, 1500));
    
    // 1. Determine main template
    let mainMatch = searchOmniIndex(p).filter(i => i.source === 'Templates' || i.source === 'Vault')[0];
    
    // If we want a health dashboard
    let isHealth = p.includes('health') || p.includes('medical') || p.includes('santé');
    let isNotepad = p.includes('notepad') || p.includes('note') || p.includes('notițe');
    let hasMockDb = p.includes('mockdb') || p.includes('baza de date') || p.includes('base de données');
    
    let baseCode = `const App = () => {
  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', background: '#f8fafc', minHeight: '100vh', padding: '40px' }}>
      <h1 style={{ color: '#0f172a' }}>✨ Generated by Aura IA PRO</h1>
      <p style={{ color: '#64748b' }}>Based on your prompt: "${prompt}"</p>
      
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px', marginTop: '40px' }}>
        {/* INJECT_ZONE */}
      </div>
    </div>
  );
};`;

    // Simulate synthesis steps
    let injectedBlocks = [];
    
    if (isHealth) {
        onProgress(isFr ? 'Extraction du layout principal de ProHealth...' : 'Extracting main layout from ProHealth...', 'extract');
        await new Promise(r => setTimeout(r, 1200));
        injectedBlocks.push(`<div style={{ background: '#fff', padding: '24px', borderRadius: '16px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)' }}>
          <h2 style={{ color: '#0ea5e9', marginTop: 0 }}>🏥 Health Dashboard</h2>
          <div style={{ fontSize: '32px', fontWeight: 'bold' }}>124 Patients</div>
          <p style={{ color: '#10b981' }}>+12% vs last week</p>
        </div>`);
    }

    if (isNotepad) {
        onProgress(isFr ? 'Recherche d\'un bloc React isolé de Notepad dans ProUtil...' : 'Searching for isolated React Notepad block from ProUtil...', 'search');
        await new Promise(r => setTimeout(r, 1000));
        onProgress(isFr ? 'Combinaison de l\'état (useState)...' : 'Combining state (useState)...', 'combine');
        await new Promise(r => setTimeout(r, 1200));
        injectedBlocks.push(`<div style={{ background: '#fff', padding: '24px', borderRadius: '16px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)' }}>
          <h2 style={{ color: '#f59e0b', marginTop: 0 }}>📝 Quick Notes</h2>
          <textarea placeholder="Type your notes here..." style={{ width: '100%', height: '100px', padding: '12px', boxSizing: 'border-box', border: '1px solid #e2e8f0', borderRadius: '8px', resize: 'none' }}></textarea>
        </div>`);
    }
    
    if (hasMockDb) {
        onProgress(isFr ? 'Insertion automatique des références MockDB...' : 'Auto-injecting MockDB references...', 'inject');
        await new Promise(r => setTimeout(r, 1400));
        injectedBlocks.push(`<div style={{ background: '#fff', padding: '24px', borderRadius: '16px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)', border: '2px solid #3ecf8e' }}>
          <h2 style={{ color: '#3ecf8e', marginTop: 0 }}>🗄️ MockDB Data</h2>
          <ul style={{ paddingLeft: '20px', color: '#475569' }}>
             <li>Record 1: Connected</li>
             <li>Record 2: Active</li>
          </ul>
        </div>`);
    }

    onProgress(isFr ? 'Assemblage des composants...' : 'Assembling components...', 'assemble');
    await new Promise(r => setTimeout(r, 1000));
    
    if (injectedBlocks.length === 0) {
        // Generic fallback
        injectedBlocks.push(`<div style={{ background: '#fff', padding: '24px', borderRadius: '16px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)' }}>
          <h2>${isFr ? 'Généré pour' : 'Generated for'}: ${p.substring(0, 20)}...</h2>
          <p>${isFr ? 'Fonctionnalité de base implémentée.' : 'Implemented core functionality.'}</p>
        </div>`);
    }

    baseCode = baseCode.replace('{/* INJECT_ZONE */}', injectedBlocks.join('\n        '));

    onProgress(isFr ? 'Terminé !' : 'Done!', 'done');
    return baseCode;
};
