(function() {
'use strict';
var t_doc = {
  en: { tab: 'Auto-Docs', title: '📚 Auto-Documentation', sub: 'Smart README from your code', gen: '⚡ Generate README', dl: '📥 Download README.md', none: 'Editor is empty — write some code first.' },
  fr: { tab: 'Auto-Doc', title: '📚 Auto-Documentation', sub: 'README intelligent depuis votre code', gen: '⚡ Générer README', dl: '📥 Télécharger README.md', none: 'L\'éditeur est vide — écrivez du code d\'abord.' }
};
function gl() { return window.lang || 'en'; }
function t(k) { return t_doc[gl()][k] || k; }

function analyzeCode(code) {
  var isFr = gl() === 'fr';
  var low = code.toLowerCase();

  // Detect project type
  var projectType = isFr ? 'Application Web' : 'Web Application';
  var features = [];
  var tech = ['HTML5', 'CSS3'];

  if (low.includes('<canvas')) { projectType = isFr ? 'Application Canvas / Graphique' : 'Canvas / Graphics App'; tech.push('Canvas API'); }
  if (low.includes('three.js') || low.includes('scene')) { projectType = isFr ? 'Scène 3D Interactive' : '3D Interactive Scene'; tech.push('Three.js'); }
  if (low.includes('fetch(') || low.includes('axios')) { tech.push('REST API'); features.push(isFr ? 'Récupération de données via API' : 'API data fetching'); }
  if (low.includes('localstorage')) { tech.push('LocalStorage'); features.push(isFr ? 'Persistance des données locales' : 'Local data persistence'); }
  if (low.includes('<video') || low.includes('<audio')) { tech.push('Media API'); features.push(isFr ? 'Lecture multimédia intégrée' : 'Integrated multimedia playback'); }
  if (low.includes('chart') || low.includes('graph')) { tech.push('Data Visualization'); features.push(isFr ? 'Visualisation de données / graphiques' : 'Data visualization / charts'); }
  if (low.includes('<form') || low.includes('submit')) { features.push(isFr ? 'Formulaire interactif' : 'Interactive form'); }
  if (low.includes('dark') || low.includes('theme')) { features.push(isFr ? 'Mode sombre / thème dynamique' : 'Dark mode / dynamic theme'); }
  if (low.includes('animation') || low.includes('@keyframes')) { features.push(isFr ? 'Animations CSS avancées' : 'Advanced CSS animations'); }
  if (low.includes('<nav') || low.includes('navbar')) { features.push(isFr ? 'Navigation multi-pages' : 'Multi-page navigation'); }
  if (low.includes('grid') || low.includes('flex')) { features.push(isFr ? 'Mise en page responsive (Grid/Flex)' : 'Responsive layout (Grid/Flex)'); }
  if (code.includes('<script')) tech.push('JavaScript');
  if (features.length === 0) features.push(isFr ? 'Interface utilisateur interactive' : 'Interactive user interface');

  // Count elements
  var htmlEls = (code.match(/<[a-z]+/gi) || []).length;
  var scripts = (code.match(/<script/gi) || []).length;
  var styles = (code.match(/<style/gi) || []).length;
  var imgs = (code.match(/<img/gi) || []).length;
  var buttons = (code.match(/<button/gi) || []).length;
  var h1Match = code.match(/<h1[^>]*>(.*?)<\/h1>/i);
  var titleMatch = code.match(/<title>(.*?)<\/title>/i);
  var projectName = (titleMatch && titleMatch[1]) || (h1Match && h1Match[1]) || (isFr ? 'Mon Projet' : 'My Project');
  projectName = projectName.replace(/<[^>]+>/g, '').trim();

  return { projectType, features, tech, htmlEls, scripts, styles, imgs, buttons, projectName };
}

function generateReadme(code) {
  var isFr = gl() === 'fr';
  var a = analyzeCode(code);
  var now = new Date().toLocaleDateString(isFr ? 'fr-FR' : 'en-US');

  var badge = '[![Built with IA Architecte](https://img.shields.io/badge/Built%20with-IA%20Architecte-blue)](https://github.com/ia-architecte)';

  var md = (isFr ? '# 📁 ' : '# 📁 ') + a.projectName + '\n\n';
  md += badge + '\n\n';
  md += '> ' + (isFr ? 'Généré automatiquement par IA Architecte — ' : 'Auto-generated by IA Architecte — ') + now + '\n\n';
  md += '---\n\n';

  md += (isFr ? '## 🧠 Type de projet\n\n' : '## 🧠 Project Type\n\n');
  md += '**' + a.projectType + '**\n\n';

  md += (isFr ? '## ⚙️ Technologies utilisées\n\n' : '## ⚙️ Technologies Used\n\n');
  a.tech.forEach(function(t) { md += '- ' + t + '\n'; });
  md += '\n';

  md += (isFr ? '## ✨ Fonctionnalités\n\n' : '## ✨ Features\n\n');
  a.features.forEach(function(f) { md += '- ' + f + '\n'; });
  md += '\n';

  md += (isFr ? '## 📊 Structure du code\n\n' : '## 📊 Code Structure\n\n');
  md += '| ' + (isFr ? 'Élément' : 'Element') + ' | ' + (isFr ? 'Nombre' : 'Count') + ' |\n';
  md += '|---|---|\n';
  md += '| ' + (isFr ? 'Balises HTML' : 'HTML Tags') + ' | ' + a.htmlEls + ' |\n';
  md += '| ' + (isFr ? 'Blocs Script' : 'Script Blocks') + ' | ' + a.scripts + ' |\n';
  md += '| ' + (isFr ? 'Blocs Style' : 'Style Blocks') + ' | ' + a.styles + ' |\n';
  md += '| Images | ' + a.imgs + ' |\n';
  md += '| Buttons | ' + a.buttons + ' |\n\n';

  md += (isFr ? '## 🚀 Démarrage rapide\n\n' : '## 🚀 Quick Start\n\n');
  md += '```bash\n';
  md += '# ' + (isFr ? 'Pas d\'installation requise' : 'No installation required') + '\n';
  md += '# ' + (isFr ? 'Ouvrez simplement index.html dans votre navigateur' : 'Simply open index.html in your browser') + '\n';
  md += 'open index.html\n```\n\n';

  md += (isFr ? '## 📝 Licence\n\n' : '## 📝 License\n\n');
  md += 'MIT © ' + new Date().getFullYear() + ' — ' + a.projectName + '\n\n';
  md += '---\n';
  md += '*' + (isFr ? 'Documenté avec ❤️ par IA Architecte Studio' : 'Documented with ❤️ by IA Architecte Studio') + '*\n';

  return md;
}

var currentMd = '';

function renderDocsTab(md) {
  var parent = document.getElementById('left-body');
  if(!parent) return;
  parent.innerHTML = '';
  var wrap = document.createElement('div');
  wrap.style = 'display:flex;flex-direction:column;height:100%;overflow:hidden;background:#0f172a;';

  var hdr = document.createElement('div');
  hdr.style = 'padding:12px 14px 8px;border-bottom:1px solid rgba(99,102,241,0.25);flex-shrink:0;';
  hdr.innerHTML = '<div style="font-size:13px;font-weight:900;color:#818cf8;">' + t('title') + '</div><div style="font-size:10px;color:#64748b;margin-top:2px;">' + t('sub') + '</div>';
  wrap.appendChild(hdr);

  var body = document.createElement('div');
  body.style = 'flex:1;overflow-y:auto;padding:12px;display:flex;flex-direction:column;gap:12px;';

  var btn = document.createElement('button');
  btn.innerHTML = t('gen');
  btn.style = 'width:100%;background:linear-gradient(90deg,#4f46e5,#7c3aed);color:#fff;border:none;padding:10px;border-radius:8px;font-weight:bold;cursor:pointer;';
  btn.onclick = function() {
    if (!window.editor) return;
    var code = window.editor.getValue();
    if (!code || !code.trim()) {
      if(window.showToast) window.showToast(t('none'));
      return;
    }
    currentMd = generateReadme(code);
    renderDocsTab(currentMd);
  };
  body.appendChild(btn);

  if (md) {
    var pre = document.createElement('pre');
    pre.style = 'background:#000;color:#94a3b8;padding:12px;border-radius:8px;font-size:10px;white-space:pre-wrap;border:1px solid #334155;overflow-y:auto;flex:1;max-height:400px;';
    pre.textContent = md;
    body.appendChild(pre);

    var dlBtn = document.createElement('button');
    dlBtn.textContent = t('dl');
    dlBtn.style = 'width:100%;background:none;border:1px solid #4f46e5;color:#818cf8;padding:8px;border-radius:8px;font-size:11px;cursor:pointer;';
    dlBtn.onclick = function() {
      var a = document.createElement('a');
      a.href = 'data:text/markdown;charset=utf-8,' + encodeURIComponent(md);
      a.download = 'README.md';
      a.click();
      if(window.showToast) window.showToast(gl()==='fr'?'README.md téléchargé!':'README.md downloaded!');
    };
    body.appendChild(dlBtn);
  }

  wrap.appendChild(body);
  parent.appendChild(wrap);
}

document.addEventListener('DOMContentLoaded', function() {
  var oAL = window.applyLang;
  window.applyLang = function() { if(typeof oAL==='function') oAL(); var el = document.getElementById('lbl-tab-autodocs'); if(el) el.textContent = t('tab'); if(window.activeTab==='autodocs') renderDocsTab(currentMd); };
  var oRT = window.renderTab;
  window.renderTab = function(tab) {
    if(tab==='autodocs') { window.activeTab='autodocs'; document.querySelectorAll('.ltab').forEach(function(b){b.classList.remove('active');}); var el=document.getElementById('tab-autodocs'); if(el) el.classList.add('active'); renderDocsTab(currentMd); return; }
    if(typeof oRT==='function') oRT(tab);
  };
});
})();
