(function() {
'use strict';
var t_nl = {
  en: {
    tab: 'Node Logic', title: '🔗 Visual Node Builder', sub: 'Connect logic blocks → compile to JS',
    compile: '⚡ Compile Logic to JS', inject: '⬇️ Inject into Editor', copy: '📋 Copy Code',
    copied: '✅ Copied!', addNode: '+ Add Node',
    nodeTypes: {
      'click': 'On Click', 'load': 'On Page Load', 'key': 'On Key Press',
      'wait': 'Wait (ms)', 'log': 'Console Log', 'alert': 'Show Alert',
      'color': 'Change Color', 'hide': 'Hide Element', 'show': 'Show Element',
      'fetch': 'Fetch URL', 'store': 'Save to Storage', 'text': 'Change Text'
    }
  },
  fr: {
    tab: 'Logique Visuelle', title: '🔗 Constructeur de Nœuds', sub: 'Connectez des blocs → compilez en JS',
    compile: '⚡ Compiler en JS', inject: '⬇️ Injecter dans l\'Éditeur', copy: '📋 Copier Code',
    copied: '✅ Copié!', addNode: '+ Nœud',
    nodeTypes: {
      'click': 'Au Clic', 'load': 'Au Chargement', 'key': 'Touche Clavier',
      'wait': 'Attendre (ms)', 'log': 'Console Log', 'alert': 'Afficher Alerte',
      'color': 'Changer Couleur', 'hide': 'Masquer Élément', 'show': 'Afficher Élément',
      'fetch': 'Charger URL', 'store': 'Sauvegarder', 'text': 'Changer Texte'
    }
  }
};
function gl() { return window.lang || 'en'; }
function t(k) { return t_nl[gl()][k] || k; }
function tNode(k) { return t_nl[gl()].nodeTypes[k] || k; }

var NODE_COLORS = {
  click: '#ef4444', load: '#f97316', key: '#f59e0b',
  wait: '#3b82f6', log: '#10b981', alert: '#8b5cf6',
  color: '#ec4899', hide: '#64748b', show: '#14b8a6',
  fetch: '#06b6d4', store: '#6366f1', text: '#84cc16'
};

var NODE_TYPES_EVENT = ['click', 'load', 'key'];
var NODE_TYPES_ACTION = ['wait', 'log', 'alert', 'color', 'hide', 'show', 'fetch', 'store', 'text'];
var ALL_TYPES = NODE_TYPES_EVENT.concat(NODE_TYPES_ACTION);

// Default node chain
var nodes = [
  { id: 0, type: 'click', param: '' },
  { id: 1, type: 'wait', param: '500' },
  { id: 2, type: 'color', param: '#3b82f6' }
];
var nextId = 3;
var generatedCode = '';

function compileNodes() {
  var isFr = gl() === 'fr';
  var lines = [];
  lines.push('// ' + (isFr ? 'Logique générée par Node Logic Builder' : 'Logic generated by Node Logic Builder'));
  lines.push('(function() {');

  var eventNode = nodes.find(function(n) { return NODE_TYPES_EVENT.indexOf(n.type) !== -1; });
  var actionNodes = nodes.filter(function(n) { return NODE_TYPES_ACTION.indexOf(n.type) !== -1; });

  var inner = [];
  actionNodes.forEach(function(n) {
    switch(n.type) {
      case 'wait':   inner.push('await new Promise(r => setTimeout(r, ' + (parseInt(n.param) || 500) + '));'); break;
      case 'log':    inner.push('console.log("' + (n.param || 'Node Logic') + '");'); break;
      case 'alert':  inner.push('alert("' + (n.param || 'Hello!') + '");'); break;
      case 'color':  inner.push('document.body.style.background = "' + (n.param || '#3b82f6') + '";'); break;
      case 'hide':   inner.push('var el = document.querySelector("' + (n.param || 'h1') + '"); if(el) el.style.display="none";'); break;
      case 'show':   inner.push('var el = document.querySelector("' + (n.param || 'h1') + '"); if(el) el.style.display="block";'); break;
      case 'fetch':  inner.push('const res = await fetch("' + (n.param || 'https://jsonplaceholder.typicode.com/posts/1') + '"); const data = await res.json(); console.log(data);'); break;
      case 'store':  inner.push('localStorage.setItem("node_data_' + n.id + '", JSON.stringify({ts: Date.now()}));'); break;
      case 'text':   inner.push('var parts = "' + (n.param || 'h1|Hello World') + '".split("|"); var elT = document.querySelector(parts[0]); if(elT) elT.textContent = parts[1] || "Hello";'); break;
    }
  });

  var funcBody = inner.map(function(l) { return '    ' + l; }).join('\n');
  var asyncFn = '  const run = async () => {\n' + funcBody + '\n  };';

  if (!eventNode || eventNode.type === 'load') {
    lines.push(asyncFn);
    lines.push('  document.addEventListener("DOMContentLoaded", run);');
  } else if (eventNode.type === 'click') {
    lines.push(asyncFn);
    lines.push('  document.addEventListener("click", run);');
  } else if (eventNode.type === 'key') {
    lines.push(asyncFn);
    lines.push('  document.addEventListener("keydown", run);');
  }

  lines.push('})();');
  return '<script>\n' + lines.join('\n') + '\n</script>';
}

function renderNodeTab() {
  var parent = document.getElementById('left-body');
  if(!parent) return;
  parent.innerHTML = '';
  var wrap = document.createElement('div');
  wrap.style = 'display:flex;flex-direction:column;height:100%;overflow:hidden;background:#0f172a;';

  var hdr = document.createElement('div');
  hdr.style = 'padding:10px 14px;border-bottom:1px solid rgba(245,158,11,0.25);flex-shrink:0;display:flex;justify-content:space-between;align-items:center;';
  var hdrLeft = document.createElement('div');
  hdrLeft.innerHTML = '<div style="font-size:13px;font-weight:900;color:#fcd34d;">' + t('title') + '</div><div style="font-size:10px;color:#94a3b8;">' + t('sub') + '</div>';
  
  var addBtn = document.createElement('button');
  addBtn.textContent = t('addNode');
  addBtn.style = 'background:#f59e0b;color:#000;border:none;padding:5px 8px;border-radius:5px;font-size:9px;font-weight:bold;cursor:pointer;';
  addBtn.onclick = function() {
    var types = ALL_TYPES;
    var chosen = types[nodes.length % types.length];
    nodes.push({ id: nextId++, type: chosen, param: '' });
    renderNodeTab();
  };
  hdr.appendChild(hdrLeft); hdr.appendChild(addBtn);
  wrap.appendChild(hdr);

  var body = document.createElement('div');
  body.style = 'flex:1;overflow-y:auto;padding:10px;display:flex;flex-direction:column;gap:6px;';

  // SVG connector arrows
  nodes.forEach(function(node, ni) {
    var card = document.createElement('div');
    card.style = 'background:#1e293b;border:2px solid ' + (NODE_COLORS[node.type] || '#475569') + ';border-radius:8px;padding:8px;display:flex;align-items:center;gap:8px;';

    var typeLabel = document.createElement('div');
    typeLabel.style = 'flex-shrink:0;font-size:9px;font-weight:bold;color:#fff;background:' + (NODE_COLORS[node.type] || '#475569') + ';padding:3px 7px;border-radius:5px;min-width:50px;text-align:center;';
    typeLabel.textContent = tNode(node.type);

    var sel = document.createElement('select');
    sel.style = 'background:#0f172a;color:#94a3b8;border:1px solid #475569;padding:3px;border-radius:4px;font-size:10px;';
    ALL_TYPES.forEach(function(tp) {
      var opt = document.createElement('option');
      opt.value = tp; opt.textContent = tNode(tp);
      if (tp === node.type) opt.selected = true;
      sel.appendChild(opt);
    });
    sel.onchange = function() { node.type = this.value; renderNodeTab(); };

    var paramInp = document.createElement('input');
    paramInp.value = node.param;
    paramInp.placeholder = getParamPlaceholder(node.type);
    paramInp.style = 'flex:1;background:#0f172a;color:#e2e8f0;border:1px solid #475569;padding:4px;border-radius:4px;font-size:10px;';
    paramInp.onchange = function() { node.param = this.value; };

    var delBtn = document.createElement('button');
    delBtn.textContent = '✕';
    delBtn.style = 'background:none;border:none;color:#ef4444;cursor:pointer;font-size:12px;font-weight:bold;';
    delBtn.onclick = function() { nodes.splice(ni, 1); renderNodeTab(); };

    card.appendChild(typeLabel); card.appendChild(sel); card.appendChild(paramInp); card.appendChild(delBtn);
    body.appendChild(card);

    if (ni < nodes.length - 1) {
      var arrow = document.createElement('div');
      arrow.style = 'text-align:center;color:#fcd34d;font-size:14px;line-height:1;';
      arrow.textContent = '↓';
      body.appendChild(arrow);
    }
  });

  var compileBtn = document.createElement('button');
  compileBtn.innerHTML = t('compile');
  compileBtn.style = 'width:100%;background:#f59e0b;color:#000;border:none;padding:10px;border-radius:8px;font-weight:900;cursor:pointer;margin-top:8px;';
  compileBtn.onclick = function() {
    generatedCode = compileNodes();
    showCodeResult(body, generatedCode);
  };
  body.appendChild(compileBtn);

  if (generatedCode) showCodeResult(body, generatedCode);

  wrap.appendChild(body);
  parent.appendChild(wrap);
}

function getParamPlaceholder(type) {
  var map = { wait: 'ms (e.g. 1000)', log: 'message', alert: 'message', color: '#hex or name', hide: 'CSS selector', show: 'CSS selector', fetch: 'URL', store: '', text: 'selector|text', click: '', load: '', key: '' };
  return map[type] || '';
}

function showCodeResult(body, code) {
  var old = document.getElementById('nl-result-zone');
  if (old) old.remove();
  var zone = document.createElement('div');
  zone.id = 'nl-result-zone';
  zone.style = 'display:flex;flex-direction:column;gap:6px;margin-top:4px;';

  var pre = document.createElement('pre');
  pre.style = 'background:#000;color:#94a3b8;padding:8px;border-radius:6px;font-size:9px;overflow-x:auto;white-space:pre-wrap;border:1px solid #334155;max-height:150px;';
  pre.textContent = code;
  zone.appendChild(pre);

  var btnRow = document.createElement('div');
  btnRow.style = 'display:flex;gap:6px;';

  var btnCopy = document.createElement('button');
  btnCopy.textContent = t('copy');
  btnCopy.style = 'flex:1;background:#334155;color:#e2e8f0;border:none;padding:7px;border-radius:5px;font-size:10px;cursor:pointer;';
  btnCopy.onclick = function() {
    navigator.clipboard.writeText(code);
    btnCopy.textContent = t('copied');
    setTimeout(function() { btnCopy.textContent = t('copy'); }, 2000);
  };

  var btnInj = document.createElement('button');
  btnInj.textContent = t('inject');
  btnInj.style = 'flex:1;background:#f59e0b;color:#000;border:none;padding:7px;border-radius:5px;font-size:10px;font-weight:bold;cursor:pointer;';
  btnInj.onclick = function() {
    if (!window.editor) return;
    var edCode = window.editor.getValue();
    if (edCode.includes('</body>')) {
      window.editor.setValue(edCode.replace('</body>', '\n' + code + '\n</body>'));
    } else {
      window.editor.setValue(edCode + '\n' + code);
    }
    if (window.runPreview) window.runPreview();
    if (window.showToast) window.showToast(gl()==='fr'?'Logique injectée!':'Logic injected!');
  };

  btnRow.appendChild(btnCopy); btnRow.appendChild(btnInj);
  zone.appendChild(btnRow);
  body.appendChild(zone);
}

document.addEventListener('DOMContentLoaded', function() {
  var oAL = window.applyLang;
  window.applyLang = function() { if(typeof oAL==='function') oAL(); var el = document.getElementById('lbl-tab-nodelogic'); if(el) el.textContent = t('tab'); if(window.activeTab==='nodelogic') renderNodeTab(); };
  var oRT = window.renderTab;
  window.renderTab = function(tab) {
    if(tab==='nodelogic') { window.activeTab='nodelogic'; document.querySelectorAll('.ltab').forEach(function(b){b.classList.remove('active');}); var el=document.getElementById('tab-nodelogic'); if(el) el.classList.add('active'); renderNodeTab(); return; }
    if(typeof oRT==='function') oRT(tab);
  };
});
})();
