const fs = require('fs');
const path = "c:/Users/andre/OneDrive/Bureau/IA ARCHITECTE cea bunaultra/js/extension-forge.js";
let code = fs.readFileSync(path, 'utf8');

// I will just use a regex to match from function getHTML(title... to function getContentCode()
const boilerFixed = `
function getHTML(title, emoji, desc, files) {
  const fStr = JSON.stringify(files.map(f=>({name:f.name,icon:f.icon,code:f.code})));
  return '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>'+title+'</title><style>*{box-sizing:border-box;margin:0;padding:0}body{background:#0f172a;color:#fff;font-family:Inter,sans-serif;display:flex;flex-direction:column;height:100vh}h1{color:#14b8a6;padding:16px 20px;font-size:18px;border-bottom:1px solid #1e293b;display:flex;align-items:center;gap:10px;flex-shrink:0}.file-tabs{display:flex;gap:0;border-bottom:1px solid #1e293b;overflow-x:auto;flex-shrink:0;background:#020617}.file-tab{padding:10px 16px;cursor:pointer;font-size:12px;font-weight:600;color:#64748b;border-bottom:2px solid transparent;white-space:nowrap;transition:0.2s;display:flex;align-items:center;gap:5px}.file-tab.active{color:#14b8a6;border-bottom-color:#14b8a6;background:#0f172a}.file-tab:hover{color:#94a3b8}.code-area{flex:1;overflow:auto;position:relative}.toolbar{background:#1e293b;padding:8px 15px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #334155;flex-shrink:0}.toolbar-left{display:flex;align-items:center;gap:10px}.badge{background:#14b8a622;color:#14b8a6;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:bold}.copy-btn{background:#14b8a6;border:none;color:#000;padding:6px 14px;border-radius:6px;cursor:pointer;font-size:12px;font-weight:bold;transition:0.2s}.copy-btn:hover{background:#0d9488}pre{padding:20px;font-family:"Fira Code",Consolas,monospace;font-size:13px;line-height:1.7;overflow:auto;color:#e2e8f0;white-space:pre-wrap;word-break:break-all}.kw{color:#818cf8}.fn{color:#34d399}.str{color:#fb923c}.cm{color:#475569;font-style:italic}.num{color:#f472b6}.punc{color:#94a3b8}.tag{color:#60a5fa}.attr{color:#34d399}.val{color:#fb923c}</style></head><body>'
+'<h1>'+emoji+' '+title+'<span style="font-size:12px;color:#64748b;font-weight:400">— '+desc+'</span></h1>'
+'<div class="file-tabs">'+files.map((f,i)=>'<div class="file-tab'+(i===0?' active':'')+'" onclick="showFile('+i+',this)">'+f.icon+' '+f.name+'</div>').join('')+'</div>'
+'<div class="toolbar"><div class="toolbar-left"><span id="curFile" class="badge">'+files[0].icon+' '+files[0].name+'</span><span style="color:#64748b;font-size:11px">Click a tab to switch files</span></div><button class="copy-btn" onclick="copyCode()">📋 Copy File</button></div>'
+'<div class="code-area"><pre id="codeBlock"></pre></div>'
+'<script>const files='+fStr+';let cur=0;function hl(code,name){let c=code.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");if(name.endsWith(".json")){c=c.replace(/"([^"]+)":/g,\'<span class="str">"$1"</span>:\').replace(/: "([^"]+)"/g,\': <span class="val">"$1"</span>\');}else if(name.endsWith(".html")){c=c.replace(/&lt;(\\/??)([a-zA-Z0-9]+)/g,\'&lt;$1<span class="tag">$2</span>\').replace(/([a-zA-Z0-9-]+)=/g,\'<span class="attr">$1</span>=\').replace(/"([^"]*)"/g,\'<span class="str">"$1"</span>\');}else{c=c.replace(/(import|export|from|const|let|async|await|return|function|default|null|false|true|chrome|console|document|window|alert|if|else|switch|case|break)\\b/g,\'<span class="kw">$1</span>\');c=c.replace(/\\/\\/.*$/gm,\'<span class="cm">$&</span>\');c=c.replace(/\\\'([^\\\']*)\\\'/g,\'<span class="str">\\\'$1\\\'</span>\').replace(/"([^"]*)"/g,\'<span class="str">"$1"</span>\');}return c;}function showFile(i,el){cur=i;document.querySelectorAll(".file-tab").forEach(t=>t.classList.remove("active"));el.classList.add("active");document.getElementById("curFile").textContent=files[i].icon+" "+files[i].name;document.getElementById("codeBlock").innerHTML=hl(files[i].code,files[i].name);}function copyCode(){navigator.clipboard.writeText(files[cur].code).then(()=>{const b=document.querySelector(".copy-btn");b.textContent="✅ Copied!";setTimeout(()=>b.textContent="📋 Copy File",2000);});}showFile(0,document.querySelectorAll(".file-tab")[0]);<\\/script></body></html>\';\n}

function getBoilerplateCode(){
const manifest = `{\\n  "manifest_version": 3,\\n  "name": "My Extension",\\n  "version": "1.0.0",\\n  "description": "A powerful Chrome extension built with Extension Forge",\\n  "permissions": ["activeTab", "storage", "contextMenus", "notifications"],\\n  "host_permissions": ["<all_urls>"],\\n  "action": {\\n    "default_popup": "popup/popup.html",\\n    "default_icon": {\\n      "16": "icons/icon16.png",\\n      "48": "icons/icon48.png",\\n      "128": "icons/icon128.png"\\n    },\\n    "default_title": "My Extension"\\n  },\\n  "background": {\\n    "service_worker": "background/background.js"\\n  },\\n  "content_scripts": [\\n    {\\n      "matches": ["<all_urls>"],\\n      "js": ["content/content.js"],\\n      "css": ["content/content.css"],\\n      "run_at": "document_idle"\\n    }\\n  ],\\n  "options_page": "options/options.html",\\n  "icons": {\\n    "16": "icons/icon16.png",\\n    "48": "icons/icon48.png",\\n    "128": "icons/icon128.png"\\n  }\\n}`;
const bg = `chrome.runtime.onInstalled.addListener(() => {\\n  console.log('Extension installed!');\\n  chrome.storage.sync.set({\\n    enabled: true,\\n    theme: 'dark',\\n    notifications: true\\n  });\\n  chrome.contextMenus.create({\\n    id: 'myExtension',\\n    title: 'My Extension Action',\\n    contexts: ['selection']\\n  });\\n});\\n\\nchrome.runtime.onMessage.addListener((message, sender, sendResponse) => {\\n  if (message.type === 'GET_DATA') {\\n    sendResponse({ data: 'Hello from background!' });\\n  }\\n  return true;\\n});\\n\\nchrome.contextMenus.onClicked.addListener((info, tab) => {\\n  if (info.menuItemId === 'myExtension') {\\n    chrome.tabs.sendMessage(tab.id, {\\n      type: 'CONTEXT_ACTION',\\n      selectedText: info.selectionText\\n    });\\n  }\\n});`;
return getHTML('Extension Boilerplate', '📦', 'Complete manifest.json + background script structure', [{name:'manifest.json',icon:'📄',code:manifest},{name:'background.js',icon:'⚙️',code:bg}]);
}
`;

code = code.replace(/function getHTML\([\s\S]*?(?=function getContentCode\(\))/m, boilerFixed);
fs.writeFileSync(path, code);
console.log("Replaced cleanly!");
